<?php
/**
 * CommentCheckModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SiapepFranceAskimet\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Akismet API
 *
 * Documentation of the Akismet API
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SiapepFranceAskimet\Client\Model;

use OpenApi\Annotations as OA;

/**
 * CommentCheckModel 
 *
 * @category Class
 * @package  SiapepFranceAskimet\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \JsonSerializable
 *
 * @OA\Schema(
 * )
 */
class CommentCheckModelOA implements \JsonSerializable
{

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $api_key;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $blog;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $user_ip;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $user_agent;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $referrer;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $permalink;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $comment_type;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $comment_author;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $comment_author_email;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $comment_author_url;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $comment_content;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $comment_date_gmt;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $comment_post_modified_gmt;

    /**
      * @var string
      * @OA\Property(
      *    type="string",
      * )
      */
    private $blog_lang;

    /**
     * @return string
     */
    public function getApiKey()
    {
        return $this->api_key;
    }

    /**
     * @param string $api_key api_key
     *
     * @return self
     */
    public function setApiKey($api_key)
    {
        $this->api_key = $api_key;

        return $this;
    }

    /**
     * @return string
     */
    public function getBlog()
    {
        return $this->blog;
    }

    /**
     * @param string $blog blog
     *
     * @return self
     */
    public function setBlog($blog)
    {
        $this->blog = $blog;

        return $this;
    }

    /**
     * @return string
     */
    public function getUserIp()
    {
        return $this->user_ip;
    }

    /**
     * @param string $user_ip user_ip
     *
     * @return self
     */
    public function setUserIp($user_ip)
    {
        $this->user_ip = $user_ip;

        return $this;
    }

    /**
     * @return string
     */
    public function getUserAgent()
    {
        return $this->user_agent;
    }

    /**
     * @param string $user_agent user_agent
     *
     * @return self
     */
    public function setUserAgent($user_agent)
    {
        $this->user_agent = $user_agent;

        return $this;
    }

    /**
     * @return string
     */
    public function getReferrer()
    {
        return $this->referrer;
    }

    /**
     * @param string $referrer referrer
     *
     * @return self
     */
    public function setReferrer($referrer)
    {
        $this->referrer = $referrer;

        return $this;
    }

    /**
     * @return string
     */
    public function getPermalink()
    {
        return $this->permalink;
    }

    /**
     * @param string $permalink permalink
     *
     * @return self
     */
    public function setPermalink($permalink)
    {
        $this->permalink = $permalink;

        return $this;
    }

    /**
     * @return string
     */
    public function getCommentType()
    {
        return $this->comment_type;
    }

    /**
     * @param string $comment_type comment_type
     *
     * @return self
     */
    public function setCommentType($comment_type)
    {
        $this->comment_type = $comment_type;

        return $this;
    }

    /**
     * @return string
     */
    public function getCommentAuthor()
    {
        return $this->comment_author;
    }

    /**
     * @param string $comment_author comment_author
     *
     * @return self
     */
    public function setCommentAuthor($comment_author)
    {
        $this->comment_author = $comment_author;

        return $this;
    }

    /**
     * @return string
     */
    public function getCommentAuthorEmail()
    {
        return $this->comment_author_email;
    }

    /**
     * @param string $comment_author_email comment_author_email
     *
     * @return self
     */
    public function setCommentAuthorEmail($comment_author_email)
    {
        $this->comment_author_email = $comment_author_email;

        return $this;
    }

    /**
     * @return string
     */
    public function getCommentAuthorUrl()
    {
        return $this->comment_author_url;
    }

    /**
     * @param string $comment_author_url comment_author_url
     *
     * @return self
     */
    public function setCommentAuthorUrl($comment_author_url)
    {
        $this->comment_author_url = $comment_author_url;

        return $this;
    }

    /**
     * @return string
     */
    public function getCommentContent()
    {
        return $this->comment_content;
    }

    /**
     * @param string $comment_content comment_content
     *
     * @return self
     */
    public function setCommentContent($comment_content)
    {
        $this->comment_content = $comment_content;

        return $this;
    }

    /**
     * @return string
     */
    public function getCommentDateGmt()
    {
        return $this->comment_date_gmt;
    }

    /**
     * @param string $comment_date_gmt comment_date_gmt
     *
     * @return self
     */
    public function setCommentDateGmt($comment_date_gmt)
    {
        $this->comment_date_gmt = $comment_date_gmt;

        return $this;
    }

    /**
     * @return string
     */
    public function getCommentPostModifiedGmt()
    {
        return $this->comment_post_modified_gmt;
    }

    /**
     * @param string $comment_post_modified_gmt comment_post_modified_gmt
     *
     * @return self
     */
    public function setCommentPostModifiedGmt($comment_post_modified_gmt)
    {
        $this->comment_post_modified_gmt = $comment_post_modified_gmt;

        return $this;
    }

    /**
     * @return string
     */
    public function getBlogLang()
    {
        return $this->blog_lang;
    }

    /**
     * @param string $blog_lang blog_lang
     *
     * @return self
     */
    public function setBlogLang($blog_lang)
    {
        $this->blog_lang = $blog_lang;

        return $this;
    }

    /**
     * @return array
     */
    public function jsonSerialize()
    {
        return [
            "api_key" => $this->api_key,
            "blog" => $this->blog,
            "user_ip" => $this->user_ip,
            "user_agent" => $this->user_agent,
            "referrer" => $this->referrer,
            "permalink" => $this->permalink,
            "comment_type" => $this->comment_type,
            "comment_author" => $this->comment_author,
            "comment_author_email" => $this->comment_author_email,
            "comment_author_url" => $this->comment_author_url,
            "comment_content" => $this->comment_content,
            "comment_date_gmt" => $this->comment_date_gmt,
            "comment_post_modified_gmt" => $this->comment_post_modified_gmt,
            "blog_lang" => $this->blog_lang,
        ];
    }
}
