<?php
/**
 * CommentCheckModelTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SiapepFranceAskimet\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Akismet API
 *
 * Documentation of the Akismet API
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SiapepFranceAskimet\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CommentCheckModelTest Class Doc Comment
 *
 * @category    Class
 * @description CommentCheckModel
 * @package     SiapepFranceAskimet\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CommentCheckModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CommentCheckModel"
     */
    public function testCommentCheckModel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blog"
     */
    public function testPropertyBlog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user_ip"
     */
    public function testPropertyUserIp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user_agent"
     */
    public function testPropertyUserAgent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "referrer"
     */
    public function testPropertyReferrer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "permalink"
     */
    public function testPropertyPermalink()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comment_type"
     */
    public function testPropertyCommentType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comment_author"
     */
    public function testPropertyCommentAuthor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comment_author_email"
     */
    public function testPropertyCommentAuthorEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comment_author_url"
     */
    public function testPropertyCommentAuthorUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comment_content"
     */
    public function testPropertyCommentContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comment_date_gmt"
     */
    public function testPropertyCommentDateGmt()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comment_post_modified_gmt"
     */
    public function testPropertyCommentPostModifiedGmt()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blog_lang"
     */
    public function testPropertyBlogLang()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
