<?php
/**
 * VerifyKeyModelTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SiapepFranceAskimet\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Akismet API
 *
 * Documentation of the Akismet API
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SiapepFranceAskimet\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VerifyKeyModelTest Class Doc Comment
 *
 * @category    Class
 * @description VerifyKeyModel
 * @package     SiapepFranceAskimet\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VerifyKeyModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VerifyKeyModel"
     */
    public function testVerifyKeyModel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blog"
     */
    public function testPropertyBlog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
