<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SiapepFranceAskimet\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Akismet API
 *
 * Documentation of the Akismet API
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SiapepFranceAskimet\Client\Test\Api;

use \SiapepFranceAskimet\Client\Configuration;
use \SiapepFranceAskimet\Client\ApiException;
use \SiapepFranceAskimet\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  SiapepFranceAskimet\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for call1CommentCheckPost
     *
     * Verify a comment against Akismet.
     *
     */
    public function testCall1CommentCheckPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call1SubmitHamPost
     *
     * Submit a comment identified as legitimate.
     *
     */
    public function testCall1SubmitHamPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call1SubmitSpamPost
     *
     * Submit a comment identified as spam.
     *
     */
    public function testCall1SubmitSpamPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call1VerifyKeyPost
     *
     * Verify the validity of an Akismet API key.
     *
     */
    public function testCall1VerifyKeyPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call2KeySitesPost
     *
     * Get a list of sites associated with an Akismet key.
     *
     */
    public function testCall2KeySitesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call2UsageLimitPost
     *
     * Get usage limits of the Akismet key.
     *
     */
    public function testCall2UsageLimitPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
